#!/usr/bin/bash

# Copyright 2023 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: Apache-2.0

COPYRIGHT="Copyright 2023 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>"

reuse addheader --copyright="$COPYRIGHT" \
		 --license=Apache-2.0 \
 .devcontainer/devcontainer.json \
 .dockerignore \
 .gitignore \
 .gitmodules \
 Dockerfile \
 README.md \
 helloworld/README.md \
 helloworld/helloworld.c \
 helloworld_mqtt/.vscode/c_cpp_properties.json \
 helloworld_mqtt/.vscode/launch.json \
 helloworld_mqtt/.vscode/settings.json \
 helloworld_mqtt/.vscode/tasks.json \
 helloworld_mqtt/CMakeLists.txt \
 helloworld_mqtt/main.c \
 mosquitto/.vscode/c_cpp_properties.json \
 mosquitto/.vscode/settings.json \
 mosquitto/.vscode/tasks.json \
 openssl/.vscode/c_cpp_properties.json \
 openssl/.vscode/settings.json \
 openssl/.vscode/tasks.json \

reuse addheader --copyright="$COPYRIGHT" \
		 --license=Apache-2.0 \
		 --style=c \
 workspace.code-workspace

reuse addheader --copyright="$COPYRIGHT" \
		 --license=Apache-2.0 \
		 --style=python \
 reusescript
 
