#!/bin/bash

# Copyright 2023 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
# SPDX-FileCopyrightText: 2023 
#
# SPDX-License-Identifier: Apache-2.0

echo "Detmold" | sudo -S /tmp/gdbserver :2159 /tmp/example_io
